/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentAction: typeof import('./components/CommentAction.vue')['default']
    CommentEditor: typeof import('./components/CommentEditor.vue')['default']
    CommentHeader: typeof import('./components/CommentHeader.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    CommentList: typeof import('./components/CommentList.vue')['default']
    CommentReaction: typeof import('./components/CommentReaction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
